#!/bin/env bash

############################################################################
# script to quickly copy VPN files into /etc/openvpn and enable systemd
# service; to avoid NetworkManager shortcoming w/autoconnect
#  and Gnome-keyring.
############################################################################

# Enable debugging
set -vx

USAGE="Usage: `basename $0` <dirWithVPNconfFiles>"

# Test for parameters
if [[ -z $1 ]]
then
  echo $USAGE
  exit 1;
fi

# clientfile=$1/*.ovpn

syswideconfig=/etc/openvpn
[[ -d $syswideconfig ]] || echo "Is openvpn installed on your system?"  # check openvpn installed

clientdir="$1"
cp -r $clientdir/* $syswideconfig

# conffile=$syswideconfig/*.ovpn

conffile=$syswideconfig/*.conf
servicefile=`cut -d/ -f4 $conffile |cut -f1`

if [[ -f $conffile ]]
then
  systemctl enable openvpn@$servicefile.service
fi

exit

