#!/bin/env bash

############################################################################
# WiredTree VPN install script with systemd support
############################################################################

set debugging on
set -vx

USAGE="Usage: `basename $0` <dirWithVPNclientConf>\n\t Please specify the Directory where your VPN files are located."

if [[ -z $1 ]]
then
  echo $USAGE
  exit 1
fi

syswideconfig=/etc/openvpn
[[ -d $syswideconfig ]] || echo "Is openvpn installed on your system?"  # check openvpn installed

# let's try to get the correct username, as this will be the prefix for name of client.conf file.
# It will also need to be set/changed within an option INSIDE the conf.file.
echo "Please enter your username: "
read NAME
echo "Thanks, $NAME. Here we go..."

# clientdir="$1 |tr -s"
clientdir="$1 | sed 's;/$;;'"
cp -r $clientdir/*.{crt,csr,key,conf} $syswideconfig

# TODO: update script with CORRECT vpn-client.conf file, reflecting username, etc.
# sed '/^cert/d' wiredtree.conf > wiredtree.conf2
# sed '/^key/d' wiredtree.conf > wiredtree.conf2
sed 's/


cp wiredtreeVPN.service /etc/systemd/system

systemctl enable wiredtreeVPN.service
sleep 1
systemctl restart wiredtreeVPN.service

exit
